# Generated by Django 4.0.4 on 2022-08-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='Movies')),
                ('category', models.CharField(choices=[('A', 'ACTION'), ('D', 'DRAMA'), ('R', 'ROMANCE'), ('C', 'COMEDY')], max_length=1)),
                ('language', models.CharField(choices=[('Hi', 'HINDI'), ('En', 'ENGLISH')], max_length=2)),
                ('status', models.CharField(choices=[('RA', 'RECENTLY ADDED'), ('MW', 'MOST WATCHED'), ('TR', 'TOP RATED')], max_length=2)),
                ('year_of_prod', models.DateField()),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
