# Generated by Django 4.0.4 on 2022-08-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_movie_cast_watch_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('romance', 'ROMANCE'), ('comedy', 'COMEDY')], max_length=20),
        ),
    ]
