# Generated by Django 4.0.4 on 2022-08-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('romance', 'ROMANCE'), ('comedy', 'COMEDY')], max_length=12),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('hindi', 'HINDI'), ('english', 'ENGLISH')], max_length=10),
        ),
    ]
